-- MySQL Script generated by MySQL Workbench
-- Seg 10 Fev 2020 10:00:55 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema catalogo_02
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `catalogo_02` ;

-- -----------------------------------------------------
-- Schema catalogo_02
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalogo_02` DEFAULT CHARACTER SET utf8 ;
USE `catalogo_02` ;

-- -----------------------------------------------------
-- Table `catalogo_02`.`satellite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`satellite` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`satellite` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`sensor` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`sensor` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`processing_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`processing_level` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`processing_level` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`radiometric_processing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`radiometric_processing` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`radiometric_processing` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`dataset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`dataset` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`dataset` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `satellite_id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  `processing_level_id` INT NOT NULL,
  `radiometric_processing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dataset_nivel1_idx` (`processing_level_id` ASC),
  INDEX `fk_dataset_tipo1_idx` (`radiometric_processing_id` ASC),
  INDEX `fk_dataset_satellite1_idx` (`satellite_id` ASC),
  INDEX `fk_dataset_sensor1_idx` (`sensor_id` ASC),
  UNIQUE INDEX `level_id_UNIQUE` (`processing_level_id` ASC),
  UNIQUE INDEX `type_id_UNIQUE` (`radiometric_processing_id` ASC),
  UNIQUE INDEX `satellite_id_UNIQUE` (`satellite_id` ASC),
  UNIQUE INDEX `sensor_id_UNIQUE` (`sensor_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_dataset_nivel1`
    FOREIGN KEY (`processing_level_id`)
    REFERENCES `catalogo_02`.`processing_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataset_tipo1`
    FOREIGN KEY (`radiometric_processing_id`)
    REFERENCES `catalogo_02`.`radiometric_processing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataset_satellite1`
    FOREIGN KEY (`satellite_id`)
    REFERENCES `catalogo_02`.`satellite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataset_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `catalogo_02`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`scene`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`scene` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`scene` (
  `id` VARCHAR(45) NOT NULL,
  `path` INT NULL,
  `row` INT NULL,
  `date` DATETIME NULL,
  `thumbnail` VARCHAR(200) NULL,
  `start_time` DATETIME NULL,
  `center_time` DATETIME NULL,
  `stop_time` DATETIME NULL,
  `cloud_cover_q1` INT NULL,
  `cloud_cover_q2` INT NULL,
  `cloud_cover_q3` INT NULL,
  `cloud_cover_q4` INT NULL,
  `ingest_date` DATETIME NULL,
  `center_latitude` FLOAT NULL,
  `center_longitude` FLOAT NULL,
  `bl_latitude` FLOAT NULL,
  `bl_longitude` FLOAT NULL,
  `br_latitude` FLOAT NULL,
  `br_longitude` FLOAT NULL,
  `tl_latitude` FLOAT NULL,
  `tl_longitude` FLOAT NULL,
  `tr_latitude` FLOAT NULL,
  `tr_longitude` FLOAT NULL,
  `dataset_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scene_dataset1_idx` (`dataset_id` ASC),
  CONSTRAINT `fk_scene_dataset1`
    FOREIGN KEY (`dataset_id`)
    REFERENCES `catalogo_02`.`dataset` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`country` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`country` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`city` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`city` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `area_km2` FLOAT NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `catalogo_02`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`address` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`address` (
  `id` INT NOT NULL,
  `zipcode` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `number` INT NULL,
  `complement` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `catalogo_02`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`company` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL DEFAULT 'publica',
  `operation` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`type` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`user` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `cpf` VARCHAR(30) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(30) NULL,
  `siape` VARCHAR(45) NULL COMMENT 'numero do servidor publico \nfederal o numero é o siape\ntem estadual\ne municipal',
  `date` DATETIME NULL COMMENT 'registration date',
  `password` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numeroservidor_UNIQUE` (`siape` ASC),
  INDEX `fk_user_address1_idx` (`address_id` ASC),
  INDEX `fk_user_company1_idx` (`company_id` ASC),
  INDEX `fk_user_type1_idx` (`type_id` ASC),
  CONSTRAINT `fk_user_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `catalogo_02`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `catalogo_02`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `catalogo_02`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`quality_control`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`quality_control` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`quality_control` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `observation` VARCHAR(45) NULL,
  `status` VARCHAR(2) NULL,
  `scene_id` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quality_user1_idx` (`user_id` ASC),
  INDEX `fk_quality_scene1_idx` (`scene_id` ASC),
  CONSTRAINT `fk_quality_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catalogo_02`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quality_scene1`
    FOREIGN KEY (`scene_id`)
    REFERENCES `catalogo_02`.`scene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`band`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`band` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`band` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`geometric_processing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`geometric_processing` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`geometric_processing` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`product` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`product` (
  `id` INT NOT NULL,
  `resolution` FLOAT NULL,
  `date` DATETIME NULL,
  `filename` VARCHAR(200) NULL,
  `scene_id` VARCHAR(45) NOT NULL,
  `band_id` INT NOT NULL,
  `radiometric_processing_id` INT NOT NULL,
  `geometric_processing_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_scene1_idx` (`scene_id` ASC),
  INDEX `fk_product_radiometric1_idx` (`radiometric_processing_id` ASC),
  INDEX `fk_product_band1_idx` (`band_id` ASC),
  INDEX `fk_product_geometric1_idx` (`geometric_processing_id` ASC),
  CONSTRAINT `fk_product_scene1`
    FOREIGN KEY (`scene_id`)
    REFERENCES `catalogo_02`.`scene` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_radiometric1`
    FOREIGN KEY (`radiometric_processing_id`)
    REFERENCES `catalogo_02`.`radiometric_processing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_band1`
    FOREIGN KEY (`band_id`)
    REFERENCES `catalogo_02`.`band` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_geometric1`
    FOREIGN KEY (`geometric_processing_id`)
    REFERENCES `catalogo_02`.`geometric_processing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`download`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`download` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`download` (
  `id` VARCHAR(45) NOT NULL,
  `date` DATETIME NULL,
  `ip` VARCHAR(40) NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_download_user1_idx` (`user_id` ASC),
  INDEX `fk_download_product1_idx` (`product_id` ASC),
  INDEX `fk_download_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_download_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `catalogo_02`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_download_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `catalogo_02`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_download_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `catalogo_02`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogo_02`.`satellite_has_sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogo_02`.`satellite_has_sensor` ;

CREATE TABLE IF NOT EXISTS `catalogo_02`.`satellite_has_sensor` (
  `satellite_id` INT NOT NULL,
  `sensor_id` INT NOT NULL,
  INDEX `fk_satellite_has_sensor_satellite1_idx` (`satellite_id` ASC),
  INDEX `fk_satellite_has_sensor_sensor1_idx` (`sensor_id` ASC),
  CONSTRAINT `fk_satellite_has_sensor_satellite1`
    FOREIGN KEY (`satellite_id`)
    REFERENCES `catalogo_02`.`satellite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_satellite_has_sensor_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `catalogo_02`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
